### DISCUSSION TITLE
Docker Setup

### DISCUSSION THREAD

**Discussion by foertel** [oraios/serena#244] [Q&A]
Hey,

I am trying to run serena in a docker setup. Am I correct that in the running docker container, there should be 

```
/workspaces
| - serena/
| - | - src/
| - | - serena_config.docker.yml
| - | - 
| - projects/
| - | - my_project/
```

When I run the docker container [according to the docs](https://github.com/oraios/serena/blob/2025-06-20/README.md#using-docker-experimental), I only bind mount `/workspaces/projects`. But the `serena_config.docker.yml` lays in `/workspaces/serena`. 

```
INFO:serena.agent:Loading Serena configuration from /workspaces/serena/serena_config.docker.yml
```

This folder is not bind mounted and will be `--rm` with the rest of the container on shutdown.

In another doc [over here](https://github.com/oraios/serena/blob/main/DOCKER.md#using-docker-directly) the whole `/workspace` directory is bind-mounted. I guess in the end it does not matter too much, where the projects are. Because you have to init them with their full path either way. But maybe the docs should still use one path as not to confuse ... me.

**Comment by pinionless** [comment]
I was also thinking about this issue because the instructions are not consistent for the docker deployment.
Also sometimes its "workspace", sometimes "workspaces".
This Q&A should be an "issue"

We need better, clear docker documentation
here is how I run it:
```
  serena:
    container_name: serena
    image: ghcr.io/oraios/serena:latest
    volumes:
      - ${HOME}/Docker/Serena/serena_config.docker.yml:/workspaces/serena/serena_config.docker.yml #config
      - ${HOME}/github/Project1:/workspaces/Project1
      - ${HOME}/github/Project2:/workspaces/Project2
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
      - "${SERENA_DASHBOARD_PORT:-24282}:24282"  # Dashboard port (default 0x5EDA = 24282)
    environment:
      - TZ=${TZ}
      - SERENA_DOCKER=1
    command:
      - "uv run --directory . serena-mcp-server --transport sse --port 9121 --host 0.0.0.0 --context ide-assistant"
```
